language: ruby
cache: bundler
services:
  - docker
before_install:
  - docker-compose build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RACK_ENV=test bundle exec rake db:create db:schema:load
  - bundle exec rake
  # For unknown reasons, the test-reporter fails when using docker if run in an
  # after_script section
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
  - docker-compose run ruby_server ./run_tests.sh 
  - bundle exec rubocop
notifications:
  email:
    recipients:
      - inferno@groups.mitre.org
    on_failure: change
