language: ruby
cache: bundler
services:
  - docker
before_install:
  - docker-compose build
script:
  - bundle exec rake
  # For unknown reasons, the test-reporter fails when using docker if run in an
  # after_script section
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
  - docker-compose run ruby_server bundle exec rake
  - bundle exec rubocop
notifications:
  email:
    recipients:
      - inferno@groups.mitre.org
    on_failure: change
