# Name of app
app_name: Inferno - SMART on FHIR Testing

# Show or hide tutorials
show_tutorial: true

# Useful during development to purge the database on each reload
purge_database_on_reload: false

# Disable peer SSL verification for environments that use SSL inspection
disable_verify_peer: false

app_name: Inferno - SMART on FHIR Testing

# When running in a docker containerr, we have to listen to other than just 'localhost' which is the default
bind: '0.0.0.0'

# Skip TLS tests
disable_tls_tests: false

# Default scopes
default_scopes: launch launch/patient offline_access openid profile user/*.* patient/*.*
