version: '3'
services:
  ruby_server:
    build:
      context: ./
    volumes:
      - ./config.yml:/var/www/inferno/config.yml
    depends_on:
      - bdt_service
  bdt_service:
    image: infernocommunity/inferno-bdt-service
  validator_service:
    image: infernocommunity/fhir-validator-service
  nginx_server:
    image: nginx
    volumes:
      - ./deployment-files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4567:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - ruby_server
